### ISSUE TITLE
Reading asynchronously, but firing functions synchronously

### ISSUE THREAD

**Issue by matthew-dean** [shinnn/node-read-glob#3]
I have a scenario where I need to process file contents in a sequential order. It's fine for files to load their contents asynchronously, but doing so creates an unpredictable order for the `next()` method. Is there a way to fire `next()` sequentially for file order, even if they're read out of order?

**Comment by shinnn** [comment]
```js
const results = [];

(async () => {
  await readGlob('somewhere/*').forEach(value => results.push(value));
  results.sort(yourFavoriteSortFunction);
})();
```
